apiVersion: apps/v1
kind: Deployment
metadata:
  name: postservice
  labels:
    app: postservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: postservice
  template:
    metadata:
      labels:
        app: postservice
    spec:
      containers:
      - name: postservice
        image: 901371017570.dkr.ecr.ap-northeast-2.amazonaws.com/post-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: postservice
  labels:
    app: postservice
spec:
  selector:
    app: postservice
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080