pipeline {
    agent any

    stages {
        stage('deploy') {
            steps {
              sh "cd webapp"
              sh "aws s3 cp ./ s3://s3-k8s-board-static-contents/ --recursive"
            }
        }
    }
}