pipeline {
    agent any
    environment {
        REGION = "ap-northeast-2"
        CREDENTIAL_ID = "1b85d2e9-4998-441a-9bac-da9a927e6720"
        BUCKET = ""
    }
    stages {
        stage('deploy') {
            steps {
                withAWS(region:"${REGION}",credentials:"${CREDENTIAL_ID}") {
                  sh "aws s3 cp webapp/ s3://board.emadam.shop --recursive"
                }
            }
        }
    }
}