import java.text.SimpleDateFormat

pipeline {
    agent any 
    stages {
        stage('Test') { 
            steps {
                dir("api/board") {
                    sh "./gradlew check"
                }
            }
        }
        stage('build') { 
            steps {
                dir("api/board") {
                    sh "./gradlew bootBuildImage --imageName=board-api"
                    sh "docker rmi board-api"
                }
            }
        }
        stage('Deploy') { 
            steps {
                script {
                    def dateFormat = new SimpleDateFormat("yyMMddHHmmss")
                    def DATETIME = dateFormat.format(new Date())
                }
                
                sh "echo ${DATETIME}"
            }
        }
    }
}