pipeline {
    agent any 
    environment {
        ECR_URI = "901371017570.dkr.ecr.ap-northeast-2.amazonaws.com"
        IMAGE_NAME = "board-api"
        REGION = "ap-northeast-2"
        CREDENTIAL_ID = "1b85d2e9-4998-441a-9bac-da9a927e6720"
    }
    stages {
        stage('Test') { 
            steps {
                dir("api/board") {
                    sh "./gradlew check"
                }
            }
        }
        stage('build') { 
            steps {
                dir("api/board") {
                    script {
                        ECR_IMAGE_NAME = sh (
                            script: "echo ${ECR_URI}/${IMAGE_NAME}",
                            returnStdout: true
                        ).trim()
                    }

                    sh "./gradlew bootBuildImage --imageName=${ECR_IMAGE_NAME}:${BUILD_NUMBER}"
                    sh "docker tag ${ECR_IMAGE_NAME}:${BUILD_NUMBER} ${ECR_IMAGE_NAME}:latest"

                    script {
                        docker.withRegistry("https://${ECR_URI}","ecr:${REGION}:${CREDENTIAL_ID}") {
                            docker.image("${ECR_IMAGE_NAME}:${BUILD_NUMBER}").push()
                            docker.image("${ECR_IMAGE_NAME}:latest").push()
                        }
                    }
                }
            }
        }
        stage('Deploy') { 
            steps {
                echo 'deploy'
            }
        }
    }
}