apiVersion: v1
kind: Service
metadata:
  name: board-service
  namespace: board
  labels:
    app: board-app
spec:
  selector:
    app: board-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer