name: "Continuous Integration - Spring App"
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
      - 'infra/**'
      - 'readme_image/**'
      - 'webapp/**'
      - 'api/user/**'
      - '**/.gitignore'

jobs:
  code-tests:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./api/post
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with: 
        distribution: 'zulu'
        java-version: '8'
    - name: Unit Tests
      timeout-minutes: 10
      run: ./gradlew check
  code-build:
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      contents: read
    defaults:
      run:
        working-directory: ./api/post
    needs: code-tests
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with: 
        distribution: 'zulu'
        java-version: '8'
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::901371017570:role/GithubDeployRole
        aws-region: ap-northeast-2
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - name: Build and push docker image to Amazon ECR
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: post-api
        IMAGE_TAG: ${{ github.sha }}
      run: |
        ./gradlew bootBuildImage --imageName=$REGISTRY/$REPOSITORY:$IMAGE_TAG
        docker tag $REGISTRY/$REPOSITORY:$IMAGE_TAG $REGISTRY/$REPOSITORY:latest
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
        docker push $REGISTRY/$REPOSITORY:latest
  code-deploy:
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      contents: read
    needs: code-build
    steps:
    - uses: actions/checkout@v3
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::901371017570:role/GithubDeployRole
        aws-region: ap-northeast-2
    - name: Apply manifests
      env:
        CLUSTER: blog-cluster
        REGION: ap-northeast-2
      run: |
        aws eks update-kubeconfig --region $REGION --name $CLUSTER
        kubectl apply -f ./kubernetes-manifests
    
    